// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchInOldSystem.DatabaseEntity;

namespace SearchInOldSystem.Migrations
{
    [DbContext(typeof(OldSysDBContext))]
    [Migration("20211121083100_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SearchInOldSystem.DatabaseEntity.Employees", b =>
                {
                    b.Property<DateTime?>("EnterDate")
                        .HasColumnName("ENTER_date")
                        .HasColumnType("datetime");

                    b.Property<string>("EshryNo")
                        .HasColumnName("ESHRY_NO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LtrDes")
                        .HasColumnName("LTR_DES")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("LtrNo")
                        .HasColumnName("LTR_NO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("LtrYear")
                        .HasColumnName("ltr_year")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnName("photo")
                        .HasColumnType("image");

                    b.Property<string>("SltrNo")
                        .HasColumnName("SLTR_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WplacExpno")
                        .HasColumnName("wplac_expno")
                        .HasColumnType("float");

                    b.Property<double?>("WplacRecno")
                        .HasColumnName("wplac_recno")
                        .HasColumnType("float");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SearchInOldSystem.DatabaseEntity.PostSendr", b =>
                {
                    b.Property<DateTime?>("EnterDate")
                        .HasColumnName("ENTER_date")
                        .HasColumnType("datetime");

                    b.Property<double?>("FilnoAppend")
                        .HasColumnName("FILNO_APPEND")
                        .HasColumnType("float");

                    b.Property<double?>("FlageSd")
                        .HasColumnName("FLAGE_SD")
                        .HasColumnType("float");

                    b.Property<string>("LaterInfor")
                        .HasColumnName("LATER_infor")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<double?>("LaterNo")
                        .HasColumnName("LATER_no")
                        .HasColumnType("float");

                    b.Property<string>("LtrType")
                        .HasColumnName("LTR_TYPE")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("LtrYear")
                        .HasColumnName("ltr_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OutDate")
                        .HasColumnName("OUT_date")
                        .HasColumnType("datetime");

                    b.Property<string>("PlaceoutPlacer")
                        .HasColumnName("PLACEOUT_placer")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PlaceoutRec")
                        .HasColumnName("PLACEOUT_rec")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PostTypel")
                        .HasColumnName("POST_typel")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("PostTypeno")
                        .HasColumnName("POST_typeno")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RecivDate")
                        .HasColumnName("RECIV_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ReciveDate")
                        .HasColumnName("RECIVE_DATE")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnName("RECORD_date")
                        .HasColumnType("datetime");

                    b.Property<string>("RecordNamel")
                        .HasColumnName("RECORD_namel")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double?>("RecordNameno")
                        .HasColumnName("RECORD_nameno")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TrnslatDate")
                        .HasColumnName("TRNSLAT_date")
                        .HasColumnType("datetime");

                    b.Property<string>("WplacExpl")
                        .HasColumnName("WPLAC_expl")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WplacExpno")
                        .HasColumnName("WPLAC_expno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WplacRecl")
                        .HasColumnName("WPLAC_recl")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WplacRecno")
                        .HasColumnName("WPLAC_recno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WplacTrnno")
                        .HasColumnName("WPLAC_trnno")
                        .HasColumnType("float");

                    b.ToTable("POST_SENDR");
                });
#pragma warning restore 612, 618
        }
    }
}
