//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.Archives {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ArchiveSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ArchiveSettings defaultInstance = ((ArchiveSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ArchiveSettings())));
        
        public static ArchiveSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ListColor {
            get {
                return ((global::System.Drawing.Color)(this["ListColor"]));
            }
            set {
                this["ListColor"] = value;
            }
        }
    }
}
